tap "homebrew/cask"
tap "AdoptOpenJDK/openjdk"

# applications
# TODO mac app store mas things id?
cask '1password'
cask 'cloudapp'
cask 'notion'
cask 'slack'
cask 'thingsmacsandboxhelper'
cask 'spotify'

# code / terminal
cask 'alacritty'
brew 'antibody'
brew 'neovim'
brew 'tmux'
brew 'zsh'

# programs
brew 'fzf'
brew 'ripgrep'
brew 'wget'

# dev
cask 'adoptopenjdk/openjdk/adoptopenjdk8'
cask 'adoptopenjdk11'
brew 'yarn'

# ios
brew 'swiftlint'
brew 'rbenv'
brew 'pyenv'
brew 'watchman'
