tap "homebrew/cask"
tap "planetscale/tap"
# tap "AdoptOpenJDK/openjdk"

# applications
# TODO mac app store mas things id?
# cask '1password'
# cask 'cloudapp'
cask 'notion'
cask 'slack'
cask 'spotify'

# code / terminal
cask 'alacritty'
brew 'neovim'
brew 'tmux'
brew 'zsh'
# brew 'fontforge' # for font patching

# programs
brew 'fzf'
brew 'ripgrep'
brew 'wget'
# brew 'imagemagick'
# brew 'ghostscript' # imagemagick dependency
# brew 'ngrok'

# dev
# cask 'adoptopenjdk/openjdk/adoptopenjdk8'
# cask 'adoptopenjdk11'
cask 'docker'
brew 'yarn'
# brew 'go'

# planet scale
brew 'planetscale/tap/pscale'
brew 'mysql-client'

# ios
# brew 'swiftlint'
# brew 'rbenv'
# brew 'pyenv'
# brew 'watchman'
