# Preferred editor for local and remote sessions
export EDITOR="nvim"

# Add homebrew installations to path
export PATH=/usr/local/bin:$PATH

# Add User bin directory to path
export PATH=$PATH:~/bin:~/squarespace/generated/bin:/usr/local/opt/imagemagick@6/bin

# NVM config
export NVM_DIR="/Users/jkaufman/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# rbenv config
eval "$(rbenv init -)"

# pyenv config
eval "$(pyenv init -)"

# Use ripgrep as default for fzf
export FZF_DEFAULT_COMMAND="rg --files --no-ignore-vcs --hidden -g '!{.git/*,node_modules/*,**/.git/*,**/node_modules/*,**/.next/*}'"

# Squarespace Docker Env
# Choose a directory where your different virtual environments will be stored
# export WORKON_HOME=$HOME/.virtualenvs  # Or another directory of your choice
# source /usr/local/bin/virtualenvwrapper.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jkaufman/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jkaufman/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jkaufman/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jkaufman/google-cloud-sdk/completion.zsh.inc'; fi

# LASTLY, HERE BE PLUGINS
# All plugins are installed to these dotfiles as git submodules
# We then link them via dotbot, and source them here

# sindresorhus/pure, terminal prompt
source ~/.zsh_plugins/pure/async.zsh
source ~/.zsh_plugins/pure/pure.zsh

# junegunn/fzf, fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# zsh-users/zsh-syntax-highlighting
source ~/.zsh_plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# zsh-users/zsh-history-substring-search
# must be sourced after syntax highlighting
# hist env vars
HISTSIZE=10000 # Lines of history to keep in memory for current session
HISTFILESIZE=10000 # Number of commands to save in the file
SAVEHIST=10000 # Number of history entries to save to disk
HISTFILE=~/.zsh_history # Where to save history to disk
HISTDUP=erase # Erase duplicates in the history file
# hist options - `man zshoptions`
setopt hist_ignore_dups # Ignore duplicates
setopt append_history # Append history to the history file (no overwriting)
setopt share_history # Share history across terminals
setopt inc_append_history # Immediately append to the history file, not just when a term is killed
# actually load it and bind keys
source ~/.zsh_plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
